import type { Config } from 'tailwindcss'

export default {
  content: [],
  theme: {
    extend: {
      colors: {
        primary: 'var(--primary)',
        'primary-container': 'var(--primary-container)',
        background: 'var(--background)',
        surface: 'var(--surface)',
        'on-background': 'var(--on-background)',
        'on-primary': 'var(--on-primary)',
        'on-surface': 'var(--on-surface)',
        'on-surface-variant': 'var(--on-surface-variant)',
        'surface-container': 'var(--surface-container)',
        'surface-container-low': 'var(--surface-container-low)',
        'surface-container-lowest': 'var(--surface-container-lowest)',
        error: 'var(--error)',
        'error-container': 'var(--error-container)',
        'on-error': 'var(--on-error)',
        'on-error-container': 'var(--on-error-container)',
        success: 'var(--success)',
        'success-container': 'var(--success-container)',
        'on-success': 'var(--on-success)',
        'on-success-container': 'var(--on-success-container)',
        warning: 'var(--warning)',
        'warning-container': 'var(--warning-container)',
        'on-warning': 'var(--on-warning)',
        'on-warning-container': 'var(--on-warning-container)',
        info: 'var(--info)',
        'info-container': 'var(--info-container)',
        'on-info': 'var(--on-info)',
        'on-info-container': 'var(--on-info-container)',
        outline: 'var(--outline)',
        'outline-variant': 'var(--outline-variant)',
      },
      fontFamily: {
        sans: ['var(--font-sans)', 'system-ui', 'sans-serif'],
        body: ['var(--font-sans)', 'system-ui', 'sans-serif'],
        serif: ['var(--font-serif)', 'serif'],
        headline: ['var(--font-serif)', 'serif'],
        label: ['var(--font-sans)', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
} satisfies Config
